{% set name = "diffpy.pdfgui" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_pdfgui/diffpy_pdfgui-{{ version }}.tar.gz
  # url: https://github.com/diffpy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 2ac7c32f2c3687a063757db4d035d4d309c80f05498f468a8b9fa77c91462c2f

build:
  # PDFgui not released as noarch despite having no C code
  # noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pdfgui = diffpy.pdfgui.applications.pdfgui:main
  osx_is_app: true

requirements:
  host:
    - python
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip
  run:
    - python
    - numpy
    - wxpython
    - menuinst  # [win]
    - diffpy.pdffit2
    - diffpy.structure >=3
    - diffpy.utils
    - matplotlib-base

test: 
  requires:
    - pip
    - pytest
    - pytest-mock
    - freezegun
    - python
  source_files:
    - tests
  commands:
    - pip check
    - pip list
    # FIXME: run pytest tests in headless
    # - pytest

app:
  entry: pdfgui  # [not win]
  entry: pythonw -m diffpy.pdfgui.applications.pdfgui  # [win]
  icon: pdfgui_64x64.png
  summary: materials structure analysis from Pair Distribution Function

about:
  home: https://github.com/diffpy/diffpy.pdfgui
  summary: GUI for PDF simulation and structure refinement
  license: Free To Use But Restricted
  license_file: LICENSE.rst
  description: |
    The diffpy.pdfgui package provides a graphical user interface to pdffit2 refinement engine, 
    with many powerful extensions. It is a GUI program for structure refinements to atomic pair 
    distribution function. It is capable of full-profile fitting of the atomic pair distribution 
    function derived from x-ray or neutron diffraction data and comes with built in graphical and 
    structure visualization capabilities.
  doc_url: https://www.diffpy.org/products/pdfgui.html
  dev_url: https://github.com/diffpy/diffpy.pdfgui

extra:
  recipe-maintainers:
    - bobleesj
    - dragonyanglong
    - sbillinge
