{% set name = "diffpy.pdfgui" %}
{% set version = "3.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
#  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/diffpy/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: ca07f557997173221dacc94f9b50fb8441e3d5755e01192b4ae0f28a0cea68b2

build:
  # we need egg_dir to avoid overlapping diffpy/__init__.py files.
  number: 3
#  noarch: python
#  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - pdfgui = diffpy.pdfgui.applications.pdfgui:main
  osx_is_app: true

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - six
    - matplotlib
    - wxpython
    - menuinst  # [win]
    - diffpy.pdffit2
    - diffpy.structure >=3
    - diffpy.utils

test:
  imports:
    - diffpy.pdfgui.tui
    - diffpy.pdfgui.tests
  requires:
    - pip
  commands:
    - pip check

app:
  entry: pdfgui  # [not win]
  entry: pythonw -m diffpy.pdfgui.applications.pdfgui  # [win]
  icon: pdfgui_64x64.png
  summary: materials structure analysis from Pair Distribution Function

about:
  home: https://github.com/diffpy/diffpy.pdfgui
  summary: GUI for PDF simulation and structure refinement
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  description: |
    The diffpy.pdfgui package provides a graphical user interface to pdffit2 refinement engine, 
    with many powerful extensions. It is a GUI program for structure refinements to atomic pair 
    distribution function. It is capable of full-profile fitting of the atomic pair distribution 
    function derived from x-ray or neutron diffraction data and comes with built in graphical and 
    structure visualization capabilities.
  doc_url: https://www.diffpy.org/products/pdfgui.html
  dev_url: https://github.com/diffpy/diffpy.pdfgui

extra:
  recipe-maintainers:
    - dragonyanglong
    - sbillinge
